language: python
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
matrix:
  include:
    - name: 'Python 3.6 on macOS'
      os: osx
      osx_image: xcode9.4
      language: shell
      before_install:
        - 'python --version'
        - 'pip3 install pytest --user'
        - 'pip3 install pylint --user'
        - 'pip3 install codecov --user'
      install:
        - 'pip3 install -r requirements.txt'
      script: 
        - 'python3 -m pylint kaggledatasets/ tests/ examples/'
        - 'python3 -m pytest'
      after_success: 'python3 -m codecov'
    - name: 'Python 3.7 on macOS'
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - 'python --version'
        - 'pip3 install pytest --user'
        - 'pip3 install pylint --user'
        - 'pip3 install codecov --user'
      install:
        - 'pip3 install -r requirements.txt'
      script:
        - 'python3 -m pylint kaggledatasets/ tests/ examples/' 
        - 'python3 -m pytest'
      after_success: 'python3 -m codecov'
    - name: 'Python 3.5 on Windows'
      os: windows
      language: shell
      before_install:
        - 'choco install python --version 3.5.4'
        - 'python --version'
        - 'python -m pip install --upgrade pip'
        - 'pip3 install --upgrade pytest'
        - 'pip3 install --upgrade pylint'
        - 'pip3 install codecov'
      env: 'PATH=/c/Python35:/c/Python35/Scripts:$PATH'
    - name: 'Python 3.6 on Windows'
      os: windows
      language: shell
      before_install:
        - 'choco install python --version 3.6.8'
        - 'python --version'
        - 'python -m pip install --upgrade pip'
        - 'pip3 install --upgrade pytest'
        - 'pip3 install --upgrade pylint'
        - 'pip3 install codecov'
      env: 'PATH=/c/Python36:/c/Python36/Scripts:$PATH'
    - name: 'Python 3.7 on Windows'
      os: windows
      language: shell
      before_install:
        - 'choco install python --version 3.7.4'
        - 'python --version'
        - 'python -m pip install --upgrade pip'
        - 'pip3 install --upgrade pytest'
        - 'pip3 install --upgrade pylint'
        - 'pip3 install codecov'
      env: 'PATH=/c/Python37:/c/Python37/Scripts:$PATH'
before_install:
  - 'python --version'
  - 'pip install -U pip'
  - 'pip install -U pytest'
  - 'pip install -U pylint'
  - 'pip install codecov'
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda update --yes -q conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
install:
  - 'pip install -r requirements.txt'
  - conda install -q python=$TRAVIS_PYTHON_VERSION pip requests conda-build jinja2 anaconda-client 
  - conda install --use-local kaggledatasets
script:
  - pylint kaggledatasets/ tests/ examples/ 
  - pytest
after_success:
  - codecov
  - chmod +x ./scripts/deploy_anaconda.sh
deploy:
  - provider: script
    script: ./scripts/deploy_anaconda.sh
    on:
      tags: true
    skip_cleanup: true
  # - provider: pypi
  #   twine_version: 1.12.1
  #   user: '__token__'
  #   password: $PYPI_API_TOKEN
  #   distributions: 'sdist bdist_wheel'
  #   on:
  #     branch: master
  #     python: 3.7